/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as portalPortalRouteImport } from './routes/(portal)/_portal'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as portalPortalIndexRouteImport } from './routes/(portal)/_portal.index'
import { Route as portalPortalParametrosRouteImport } from './routes/(portal)/_portal.parametros'
import { Route as portalPortalHistorialRouteImport } from './routes/(portal)/_portal.historial'
import { Route as portalPortalCrearPesajeRouteImport } from './routes/(portal)/_portal.crear-pesaje'
import { Route as portalPortalControlCalidadRouteImport } from './routes/(portal)/_portal.control-calidad'
import { Route as portalPortalClientesRouteImport } from './routes/(portal)/_portal.clientes'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'

const portalPortalRoute = portalPortalRouteImport.update({
  id: '/(portal)/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const portalPortalIndexRoute = portalPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => portalPortalRoute,
} as any)
const portalPortalParametrosRoute = portalPortalParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => portalPortalRoute,
} as any)
const portalPortalHistorialRoute = portalPortalHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => portalPortalRoute,
} as any)
const portalPortalCrearPesajeRoute = portalPortalCrearPesajeRouteImport.update({
  id: '/crear-pesaje',
  path: '/crear-pesaje',
  getParentRoute: () => portalPortalRoute,
} as any)
const portalPortalControlCalidadRoute =
  portalPortalControlCalidadRouteImport.update({
    id: '/control-calidad',
    path: '/control-calidad',
    getParentRoute: () => portalPortalRoute,
  } as any)
const portalPortalClientesRoute = portalPortalClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => portalPortalRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authAuthLoginRoute
  '/clientes': typeof portalPortalClientesRoute
  '/control-calidad': typeof portalPortalControlCalidadRoute
  '/crear-pesaje': typeof portalPortalCrearPesajeRoute
  '/historial': typeof portalPortalHistorialRoute
  '/parametros': typeof portalPortalParametrosRoute
  '/': typeof portalPortalIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authAuthLoginRoute
  '/clientes': typeof portalPortalClientesRoute
  '/control-calidad': typeof portalPortalControlCalidadRoute
  '/crear-pesaje': typeof portalPortalCrearPesajeRoute
  '/historial': typeof portalPortalHistorialRoute
  '/parametros': typeof portalPortalParametrosRoute
  '/': typeof portalPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(portal)/_portal': typeof portalPortalRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(portal)/_portal/clientes': typeof portalPortalClientesRoute
  '/(portal)/_portal/control-calidad': typeof portalPortalControlCalidadRoute
  '/(portal)/_portal/crear-pesaje': typeof portalPortalCrearPesajeRoute
  '/(portal)/_portal/historial': typeof portalPortalHistorialRoute
  '/(portal)/_portal/parametros': typeof portalPortalParametrosRoute
  '/(portal)/_portal/': typeof portalPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/clientes'
    | '/control-calidad'
    | '/crear-pesaje'
    | '/historial'
    | '/parametros'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clientes'
    | '/control-calidad'
    | '/crear-pesaje'
    | '/historial'
    | '/parametros'
    | '/'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(portal)/_portal'
    | '/(auth)/_auth/login'
    | '/(portal)/_portal/clientes'
    | '/(portal)/_portal/control-calidad'
    | '/(portal)/_portal/crear-pesaje'
    | '/(portal)/_portal/historial'
    | '/(portal)/_portal/parametros'
    | '/(portal)/_portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  portalPortalRoute: typeof portalPortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(portal)/_portal': {
      id: '/(portal)/_portal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof portalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(portal)/_portal/': {
      id: '/(portal)/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof portalPortalIndexRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(portal)/_portal/parametros': {
      id: '/(portal)/_portal/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof portalPortalParametrosRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(portal)/_portal/historial': {
      id: '/(portal)/_portal/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof portalPortalHistorialRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(portal)/_portal/crear-pesaje': {
      id: '/(portal)/_portal/crear-pesaje'
      path: '/crear-pesaje'
      fullPath: '/crear-pesaje'
      preLoaderRoute: typeof portalPortalCrearPesajeRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(portal)/_portal/control-calidad': {
      id: '/(portal)/_portal/control-calidad'
      path: '/control-calidad'
      fullPath: '/control-calidad'
      preLoaderRoute: typeof portalPortalControlCalidadRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(portal)/_portal/clientes': {
      id: '/(portal)/_portal/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof portalPortalClientesRouteImport
      parentRoute: typeof portalPortalRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface portalPortalRouteChildren {
  portalPortalClientesRoute: typeof portalPortalClientesRoute
  portalPortalControlCalidadRoute: typeof portalPortalControlCalidadRoute
  portalPortalCrearPesajeRoute: typeof portalPortalCrearPesajeRoute
  portalPortalHistorialRoute: typeof portalPortalHistorialRoute
  portalPortalParametrosRoute: typeof portalPortalParametrosRoute
  portalPortalIndexRoute: typeof portalPortalIndexRoute
}

const portalPortalRouteChildren: portalPortalRouteChildren = {
  portalPortalClientesRoute: portalPortalClientesRoute,
  portalPortalControlCalidadRoute: portalPortalControlCalidadRoute,
  portalPortalCrearPesajeRoute: portalPortalCrearPesajeRoute,
  portalPortalHistorialRoute: portalPortalHistorialRoute,
  portalPortalParametrosRoute: portalPortalParametrosRoute,
  portalPortalIndexRoute: portalPortalIndexRoute,
}

const portalPortalRouteWithChildren = portalPortalRoute._addFileChildren(
  portalPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  portalPortalRoute: portalPortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
